name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'
          
      - name: Deploy to Production
        uses: pantaSanjesh/github-actions@main
    
      - name: Publish the project to docs folder
        run: dotnet publish -c Release -o ./docs/wwwroot

      - name: Deploy to GitHub Pages
        uses: pantaSanjesh/Portfolio@v1.0.0
        with:
          publish_dir: ./docs
